### ISSUE TITLE
Robot Variable Log

### ISSUE THREAD

**Issue by jsmeldru** [hot67/RobotUtils#1]
There has been many instances where we would like to log something
during a match.  The idea to to maybe something like this.

LogData(What you want to log, the rate at which you want to log in
milliseconds);

i.e. LogData(m_rEncode->GetDistance(), 25);

**Comment by hal7df** [comment]
Should probably update this thread.

`BackgroundDebugger`'s manual log is fully functional as of `3bb4881`. Writes to a CSV file and everything.
Automatic debugging is still a WIP, though.
